correspondence/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;


namespace correspondence.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            if (Session["auth_isLogin"] == null || (bool)Session["auth_isLogin"] == false)
            {
                return RedirectToAction("Login", "Users");

            }
            
            return View();
        }

        [HttpGet]
        public ActionResult AddBook()
        {
            if (Session["auth_isLogin"] == null || (bool)Session["auth_isLogin"] == false)
            {
                return RedirectToAction("Login", "Users");

            }
            string Dept = Session["auth_Department"].ToString();
            if ((Dept == "0") || (Dept == "4"))
                ViewBag.BookNum = "110000";
            else if (Dept == "1")
                ViewBag.BookNum = "113100";
            else if (Dept == "2")
                ViewBag.BookNum = "110100";
            else if (Dept == "3")
                ViewBag.BookNum = "112000";
            else if (Dept == "5")
                ViewBag.BookNum = "114000";
            else
                ViewBag.BookNum = "1110100";

            ViewBag.alert = TempData["alert"];
            ViewBag.error = TempData["error"];
            ViewBag.BookLoc = 1; //counter for book Location
            ViewBag.BookLoc2 = 1;
            ViewBag.CopyTo = 1;
            return View();
        }

        [HttpPost]
        public ActionResult AddingBook(HttpPostedFileBase Postfile)
        {
            if (Session["auth_isLogin"] == null || (bool)Session["auth_isLogin"] == false)
            {
                return RedirectToAction("Login", "Users");

            }
            try
            {
                string Book_Num = Request["Book_Num"].ToString();
                string SaderBook_Num = Request["Book_Num2"].ToString();
                string Book_Date = Request["Book_Date"].ToString();
                string Subject = Request["Subject"].ToString();
                string BookType = Request["BookType"].ToString();
                string Destination = Request["Destination"].ToString();
                //string Status = Request["Status"].ToString();
                string Duration = Request["Duration"].ToString();
                //string Book_Response = Request["Book_Response"].ToString();
                string Wazeer_Note = Request["Wazeer_Note"].ToString();
                string Secret = Request["Secret"].ToString();
                DateTime B_Date, W_Date;
                List<string> BookLocation = new List<string>();
                List<string> CopyToList = new List<string>();
                string WardBook_Num = "";
                string WardBook_Date;
                int WardFlag = 1;
                W_Date = DateTime.Now;

                if (BookType == "1")
                {
                    WardBook_Num = Request["BookWard_Num"].ToString();
                    WardBook_Date = Request["BookWard_Date"].ToString();
                    int Wardcounter = Convert.ToInt16(Request["WardLocCounter"].ToString());
                    if (DateTime.TryParse(WardBook_Date, out W_Date) == false)
                        WardFlag = 0;
                    else
                    {
                        int i = 1;
                        while (i <= Wardcounter)
                        {
                            string WardLoc = "WardLoc" + i;
                            BookLocation.Add(Request[WardLoc].ToString());
                            i = i + 1;
                        }
                    }
                }
                else
                {
                    int Sadercounter = Convert.ToInt16(Request["SaderLocCounter"].ToString());
                    int CopyCounter = Convert.ToInt16(Request["CopyCounter"].ToString());
                    int i = 1;
                    while (i <= Sadercounter)
                    {
                        string SaderLoc = "SaderLoc" + i;
                        BookLocation.Add(Request[SaderLoc].ToString());
                        i = i + 1;
                    }

                    i = 1;
                    while (i <= CopyCounter)
                    {
                        string CopyTo = "CopyTo" + i;
                        CopyToList.Add(Request[CopyTo].ToString());
                        i = i + 1;
                    }
                }


                if ((WardFlag == 0) || (DateTime.TryParse(Book_Date, out B_Date) == false) || ((BookType == "1") && (Book_Num.ToString().Count() == 0)) || ((BookType == "2") && (SaderBook_Num.ToString().Count() == 0)) || (Book_Date.ToString().Count() == 0) || (Subject.ToString().Count() == 0))
                {
                    TempData["error"] = "حدث خطأ ، لم يتم إضافة الكتاب ... الرجاء ادخال جميع البيانات المطلوبة";
                }
                else
                {
                    Models.BookModel Books = new Models.BookModel();
                    string Attach_id = null;
                    DateTime Resp_Date = DateTime.Now;
                    int durat = 1;
                    
                    while(durat <= Convert.ToInt16(Duration))
                    {
                        Resp_Date = Resp_Date.AddDays(1);
                        if((Resp_Date.DayOfWeek.ToString() != "Friday") && (Resp_Date.DayOfWeek.ToString() != "Saturday"))
                             durat += 1;
                    }
                    string user_id = Session["auth_userid"].ToString();
                    string book_id;
                    if (BookType == "1")
                    {

                        WardBook_Num = Request["ReadBook_Num2"].ToString() + Request["BookWard_Num"].ToString();
                        book_id = Books.AddBook(Book_Num, B_Date, Subject, BookType, Destination, "2", "", Duration, Wazeer_Note, Secret, Attach_id, Resp_Date, WardBook_Num, W_Date, user_id);
                    }
                    else
                    {
                         SaderBook_Num = Request["ReadBook_Num"].ToString() + Request["Book_Num2"].ToString();
                         book_id = Books.AddBook(SaderBook_Num, B_Date, Subject, BookType, Destination, "2", "", Duration, Wazeer_Note, Secret, Attach_id, Resp_Date, "", null, user_id);
                    }
                       

                    int Loc_id =Books.AddLocation(BookLocation, book_id, BookType);

                    if (BookType == "2")
                    {
                        int Copy_id = Books.AddCopyTo(CopyToList, book_id.ToString());
                    }

                    if ((Postfile != null) && (Postfile.ContentLength > 0) && (Convert.ToUInt64(book_id) > 0))
                    {
                        string filename = Path.GetFileName(Postfile.FileName);
                        string extention = Path.GetExtension(Postfile.FileName).ToLower();
                        String[] allowedExtensions = { ".gif", ".png", ".jpeg", ".jpg", ".doc", ".docx", ".pdf", ".fni", ".xls", ".xlt", ".xlm", ".ppt", ".pot", ".pps" };
                        if (allowedExtensions.Contains(extention))
                        {
                            using (Stream fs = Postfile.InputStream)
                            {
                                using (BinaryReader br = new BinaryReader(fs))
                                {

                                    string contenttype = Postfile.ContentType;
                                    int filesize = Postfile.ContentLength;
                                    byte[] bytes = br.ReadBytes((Int32)fs.Length);
                                    Attach_id = Books.AddOrUdateFile(bytes, filename, contenttype, filesize, book_id, 0);

                                }
                            }
                        }
                    }

                    if (Convert.ToUInt64(book_id) > 0)
                    {
                        TempData["alert"] = "تم إضافة الكتاب بنجاح";
                        int log_id = Books.AddLog(1, user_id, "Web", "", "");
                        return RedirectToAction("SearchBook");
                    }
                    else
                        TempData["alert"] = " حدث خطأ ، لم يتم إضافة الكتاب  ";
                }
                
            }
            catch
            {
                TempData["error"] = "حدث خطأ ، لم يتم إضافة الكتاب";
            }
            return RedirectToAction("AddBook");

        }

        public ActionResult SearchBook( string Book_num , string Subject , string Book_Date, int? page)
        {
            if (Session["auth_isLogin"] == null || (bool)Session["auth_isLogin"] == false)
            {
                return RedirectToAction("Login", "Users");

            }
            Models.BookModel Books = new Models.BookModel();
            string User_Dept = Session["auth_Department"].ToString();
            ViewBag.Books = Books.PrintBooks(Book_num, Subject, Book_Date, "", "", User_Dept).ToPagedList(page ?? 1, 20);
            return View(ViewBag.Books);
        }


        [HttpPost]
        public ActionResult SearchingBook()
        {
            if (Session["auth_isLogin"] == null || (bool)Session["auth_isLogin"] == false)
            {
                return RedirectToAction("Login", "Users");

            }
            string Book_num = Request["Book_num"].ToString();
            string Subject = Request["Subject"].ToString();
            string Book_Date = Request["Book_Date"].ToString();
            return RedirectToAction("SearchBook", new {  Book_num, Subject, Book_Date });
        }

        [HttpPost]
        public ActionResult DeletingBook()
        {
            if (Session["auth_isLogin"] == null || (bool)Session["auth_isLogin"] == false)
            {

correspondence/Views/Shared/_layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="~/Content/js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="~/Content/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="~/Content/js/feather.min.js"></script>
    <link href="~/Content/open-iconic/font/css/open-iconic-bootstrap.css" rel="stylesheet">
    <link href="~/Content/styles/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/Content/styles/layout.css" rel="stylesheet" type="text/css" media="all">


    <link rel="stylesheet" href="~/Content/jquery-ui-1.12.1/jquery-ui.css">
    @*<link rel="stylesheet" href="/resources/demos/style.css">*@
    <script src="~/Content/jquery-ui-1.12.1/jquery-ui.js"></script>
</head>

<body dir="rtl">
    <div class="text-center">
        <img alt="Sym" src="@Url.Content("~/Content/images/SYM.png")" />
    </div>

    <header>
        <nav class="navbar navbar-expand-md navbar-light">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarCollapse">
                <ul class="navbar-nav  justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")"><i data-feather="home"></i> الصفحة الرئيسية</a>
                    </li>
                    @if ((Session["auth_isLogin"] != null) &&((int)Session["auth_level"] == 1))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" dir="rtl">
                                <i data-feather="user"></i> المستخدمين
                            </a>



                            <div style="text-align: right;" class="dropdown-menu " aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Show", "Users")"> <i data-feather="users"></i> عرض</a>
                                <a class="dropdown-item" href="@Url.Action("Register", "Users")"> <i data-feather="plus"></i> إضافة</a>
                            </div>
                        </li>
                    }

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" dir="rtl">
                            <i data-feather="book-open"></i> الكتب
                        </a>
                        <div style="text-align: right;" class="dropdown-menu " aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("SearchBook","Book")"> <i data-feather="users"></i> استعلام</a>

                            <a class="dropdown-item" href="@Url.Action("AddBook","Book")"> <i data-feather="plus"></i> إضافة</a>

                            <a class="dropdown-item" href="@Url.Action("NotAnsweredBook","Book")"> <i data-feather="phone-missed"></i> كتب لم يتم الرد عليها</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ChangePassword", "Users")"><i data-feather="user"></i> الاعدادات</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout","Users")"><i data-feather="unlock"></i> خروج</a>
                    </li>


                </ul>

            </div>
        </nav>
    </header>

    <div class="container">
        <div class="text-center"><br />
            @RenderPage("~/Views/Shared/alert.cshtml")

            @RenderBody()
        </div>
    </div>
    <script>
        feather.replace()
    </script>
</body>
</html>

correspondence/Views/Shared/alert.cshtml
@{
    if (ViewBag.alert != null)
    {
        <fieldset>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @ViewBag.alert
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </fieldset>
    }

    if (ViewBag.error != null)
    {
        <fieldset>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                @ViewBag.error
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </fieldset>
    }
}